add missing optional param for set leverage method
sieblyio/bybit-api pull request #114
Opened 2021-09-30 01:45 UTC by jeffminsungkim

Hello, @tiagosiebler 
An optional parameter `leverage_only` requires for the following circumstance.

> Use this parameter to set leverage while in cross margin mode.
If this field is set to false, when leverage is equal to 0 the position will use cross margin; when leverage is greater than 0 the position will use isolated margin.
If this field is set to true, you can set leverage in cross margin with leverage. leverage must be greater than 0.
Use the Cross/Isolated Margin Switch endpoint to switch cross/isolated without modifying the cross level of leverage.

2021-10-03 19:27 UTC, tiagosiebler requested changes
Can you do this without the huge change in package-lock? Thanks for making the PR!

2021-10-06 12:33 UTC, jeffminsungkim commented
> Can you do this without the huge change in package-lock? Thanks for making the PR!

@tiagosiebler 
I believe it's a [standard practice to commit package-lock.json](https://stackoverflow.com/a/50868690/3252438).
Do you still want me to get rid of it?

2021-10-06 12:40 UTC, tiagosiebler commented
> @tiagosiebler I believe it's a [standard practice to commit package-lock.json](https://stackoverflow.com/a/50868690/3252438). Do you still want me to get rid of it?

While I do agree (and that's why there is one in the repo already), I'd prefer to do the update in a separate PR. Thanks

2021-10-07 14:06 UTC, jeffminsungkim commented
@tiagosiebler Alright then! I'll remove it as you said :)

2021-10-08 01:33 UTC, jeffminsungkim commented
@tiagosiebler Done!

2021-10-08 16:09 UTC, tiagosiebler approved these changes
Thanks!

2021-10-08 16:09 UTC, merged

2021-10-12 13:39 UTC, jeffminsungkim commented
@tiagosiebler 
May I ask when would it be released?

2021-10-12 17:48 UTC, tiagosiebler commented
> @tiagosiebler May I ask when would it be released?

Sorry for the delay, just pushed with the latest version `v2.1.2`. Thanks!

2021-10-26 07:18 UTC, jeffminsungkim commented
> > @tiagosiebler May I ask when would it be released?
> 
> Sorry for the delay, just pushed with the latest version `v2.1.2`. Thanks!

Thank you for the great work! :)