Fix 'POST' request on spot API and add spot web socket Private Topics support
sieblyio/bybit-api pull request #118
Opened 2021-10-07 15:29 UTC by BattlefieldDuck

#### src/util/BaseRestClient.ts 
The spot API of bybit request is a bit weird. We need to send `param` like GET request instead of `data`.
It is already implemented in pybit https://github.com/verata-veritatis/pybit/blob/master/pybit/__init__.py#L1768-L1779

#### src/websocket-client.ts
Add Web Socket Private Topics Support

2021-10-07 17:12 UTC, BattlefieldDuck commented on src/websocket-client.ts
> +    (async () => {
https://bybit-exchange.github.io/docs/spot/#t-websocketauthentication

Authenticate with API

2021-10-07 17:16 UTC, BattlefieldDuck commented on src/websocket-client.ts
> +      if ('success' in msg || msg?.pong || msg?.auth === 'success' || msg?.ping) {
Handle `{"auth":"success","userId":1234567}` and `{"ping":1633625580000}`
The spot private topic web socket reply with `{"ping":1633625580000}` instead of pong...

2021-10-07 17:16 UTC, BattlefieldDuck commented on src/websocket-client.ts
> +      } else if (Array.isArray(msg)) {
Handle all spot private topics https://bybit-exchange.github.io/docs/spot/#t-privatetopics

2021-10-09 11:44 UTC, tiagosiebler requested changes
Thanks for working on this! Some comments but otherwise great work

2021-10-09 11:44 UTC, tiagosiebler commented on src/websocket-client.ts
> +    (async () => {
Thanks for working on this! I would prefer if you just make the parent function (`onWsOpen()`) async, instead of this nested IIFE.

2021-10-09 11:44 UTC, tiagosiebler commented on src/websocket-client.ts
> +          const signature = await signMessage('GET/realtime' + expires, secret);
This part seems really similar to what `getAuthParams` does, at least a part of it. Can you find a way to reuse existing code, even if that means refactoring getAuthParams() slightly? I would prefer not to have two places doing something similar - instead similar logic should be moved to a function that both places can just call.

2021-10-09 11:44 UTC, tiagosiebler commented on src/websocket-client.ts
> +      } else if (Array.isArray(msg)) {
Good catch! I guess this will behave similarly for any existing implementation, with one event fired per event in the Array?

2021-10-09 11:44 UTC, tiagosiebler commented on src/websocket-client.ts
> +      if ('success' in msg || msg?.pong || msg?.auth === 'success' || msg?.ping) {
Does `onWsMessageResponse` need any extra handling to process a { ping } msg (send back a pong)? The docs only mention sending pings every 30 seconds, so maybe this logic in onWsMessageResponse can just send a ping when it receives a ping. Doesn't cost anything, as far as I can tell.

2021-10-09 14:12 UTC, BattlefieldDuck commented on src/websocket-client.ts
> +      if ('success' in msg || msg?.pong || msg?.auth === 'success' || msg?.ping) {
If I don't add `msg?.ping`, I get
```sh
[ 'Sending ping', { category: 'bybit-ws', wsKey: 'spotPrivate' } ]
[
  'Sending upstream ws message: ',
  {
    category: 'bybit-ws',
    wsMessage: '{"op":"ping"}',
    wsKey: 'spotPrivate'
  }
]
[ 'Received pong', { category: 'bybit-ws', wsKey: 'spotPrivate' } ]
[
  'Got unhandled ws message',
  {
    category: 'bybit-ws',
    message: { ping: 1633788480000 },
    event: MessageEvent {
      target: [WebSocket],
      type: 'message',
      data: '{"ping":1633788480000}'
    },
    wsKey: 'spotPrivate'
  }
]
```
Adding a `msg?.ping` can filter out this message

2021-10-09 14:17 UTC, BattlefieldDuck commented on src/websocket-client.ts
> +      } else if (Array.isArray(msg)) {
`['outboundAccountInfo', 'executionReport', 'ticketInfo']` will return as an array, and I guess the array length will be always equal to `1`.

I followed the pybit implementation. https://github.com/verata-veritatis/pybit/blob/master/pybit/__init__.py#L2388-L2393

2021-10-12 18:21 UTC, BattlefieldDuck commented
To summarize..

## src/util/BaseRestClient.ts
- Remove undefined values in params variable, fixes `Signature for this request is not valid.` issue.
- Send param like `GET` request instead of data, fixes `POST` request not working with spot API issue.

## src/util/requestUtils.ts
- Filter the ping response on `spotPrivate`, fixes console spamming ping response issue.

## src/websocket-client.ts
- Support `spotPrivate` websocket

2021-10-19 19:22 UTC, tiagosiebler requested changes
Almost done, some final requests

2021-10-19 19:22 UTC, tiagosiebler commented on src/spot-client.ts
> -    return this.get('/spot/v1/trades', {
Good catch!

2021-10-19 19:22 UTC, tiagosiebler commented on src/util/BaseRestClient.ts
> +    }
I'm a bit picky here because `_call(...)` is a very important function of this connector... could you make a separate function for this? E.g you could make a `filterUndefinedValues(params: unknown)` method in src/util/requestUtils.ts.

Then you could also add a few tests to make sure it works as expected with any of the expected test cases (undefined, not an object, object with some values, nested object, array?, etc).

2021-10-19 19:22 UTC, tiagosiebler commented on src/websocket-client.ts
> +  }
A lot of this is similar to the `getAuthParams()` method in this class. Can you find a way to reuse the logic that's also in getAuthParams()? 

Perhaps we can add a second parameter to that method `getAuthParams(wsKey: WsKey, serialize: boolean)`, then `if(serialize)` return what `getAuthParams` already returns, otherwise return the `params` object (which seems to have what you need in your tryWsSend msg. 

So instead of two places generating a signature with recv window, we only have one.

2021-10-19 19:59 UTC, BattlefieldDuck commented on src/util/BaseRestClient.ts
> +    }
I figured out the problem last day. The undefined values problem only occurs on `spot-client.ts` since the data is passed through function parameters instead of a kv.

For example (https://github.com/tiagosiebler/bybit-api/blob/master/src/spot-client.ts#L125):
```ts
getOpenOrders(symbol?: string, orderId?: string, limit?: number) {
  return this.getPrivate('/spot/v1/open-orders', {
    symbol,
    orderId,
    limit,
  });
}
```
if we call `getOpenOrders('BTCUSDT')`, `{symbol: 'BTCUSDT', orderId: undefined, limit: undefined}` will be passed, and the signing of the request will contain the undefined kv and it will become invalid.

The best solution is to rewrite the function to 
```ts
getOpenOrders(params: {
  symbol?: string;
  orderId?: string;
  limit?: number;
}) {
  return this.getPrivate('/spot/v1/open-orders', params);
}
```
and call `getOpenOrders({ symbol: 'BTCUSDT' })`, the signing of the request will be valid.

I guess it is necessary to change all the functions to `params: { ... }` form to fix the problem, but changing the functions will break the v2.x.x library and need to pump to v3.x.x, so I believe
```ts
if (params) {
  // Filter undefined values
  params = Object.entries(params).reduce((a, [k, v]) => (v === undefined ? a : (a[k]=v, a)), {});
}
```
is the best temp fix for this issue.

2021-10-24 16:29 UTC, tiagosiebler commented on src/util/BaseRestClient.ts
> +    }
Yes that makes sense to me, but it would still be safer to move this one line to a pure function (e.g make and export a new function in requestUtils.ts), and then add some test coverage for the behaviours we expect from this function. Then you can call this function here instead of the one-liner.

2021-11-25 22:34 UTC, BattlefieldDuck commented on src/websocket-client.ts
> +  }
Done

2021-11-25 22:35 UTC, BattlefieldDuck commented on src/util/BaseRestClient.ts
> +    }
I had removed this temp fix for the spot client, I think I will rewrite the spot-client.ts to fully fix the undefined value issue.

2022-01-02 21:13 UTC, tiagosiebler commented
Thanks for all the work. I still have some changes in mind but I'll merge your work so far into a dev branch and continue from there. Happy for you to open a new Pr into the dev branch if oyu also had other changes to add. Thanks!

2022-01-02 21:14 UTC, merged