feat(): Update as of 17th July 2024 Release notes
sieblyio/bybit-api pull request #359
Opened 2024-07-17 12:30 UTC by JJ-Cro

Added convert endpoints
Added convert examples
Small additions to params and responses - no breaking changes.

2024-07-17 12:31 UTC, JJ-Cro commented on src/rest-client-v5.ts
> +  /**
This is new function that I added since I cannot test. Possibly old one works, but I doubt much people use this endpoint anyways since it is institutional only. I have marked some comments with explanation in case people wonder if it doesnt work.

2024-07-25 08:13 UTC, tiagosiebler requested changes
Looks great! Minor requests, otherwise this is perfect

2024-07-25 08:13 UTC, tiagosiebler commented on package-lock.json
> +      "version": "3.10.11",
Can you run `npm install` and commit the updated package-lock? It's still referring to the previous version (must be that you ran npm install before updating the version in package.json

2024-07-25 08:13 UTC, tiagosiebler commented on src/rest-client-v5.ts
> +  }
Please use object params to reduce future pains.
```suggestion
  setDisconnectCancelAllWindowV2(params: { 
    product: 'OPTION' | 'SPOT' | 'DERIVATIVES',
    timeWindow: number,
  }): Promise<APIResponseV3<undefined>> {
    return this.postPrivate('/v5/order/disconnected-cancel-all', params);
  }
```

2024-07-25 14:57 UTC, tiagosiebler approved these changes
LGTM, thanks!

2024-07-25 14:58 UTC, merged